[package]
name = "rid64"
authors = ["Shaun Priestley <shaun@cksm.cc>"]
version = "1.0.0-alpha.1"
edition = "2021"
description = "A library for efficiently representing and transmitting 64 bit random ID's"
repository = "https://github.com/shauncksm/rid64"
categories = ["data-structures", "encoding", "web-programming"]
license = "MIT OR Apache-2.0"
publish = false

[features]
rand = ["dep:rand"]

[dependencies]
rand = { version = "0.8.5", optional = true, default-features = false}

[dev-dependencies]
criterion = { version = "0.3.6", features = [ "html_reports" ] }
rand = { version = "0.8.5" }

[[bench]]
name = "id64"
harness = false