[package]
name = "base64id"
authors = ["Shaun Priestley <shaun@cksm.cc>"]
version = "0.1.0"
edition = "2021"
description = "A library for generating and representing 64 bit integers as base64url strings"
repository = "https://github.com/shauncksm/base64id-rs"
readme = "README.md"
categories = ["data-structures", "encoding", "web-programming", "no-std", "value-formatting"]
keywords = ["base64", "base64url"]
license = "MIT OR Apache-2.0"

[features]
rand = ["dep:rand"]
serde = ["dep:serde"]
sqlx = ["dep:sqlx", "std"]
std = []

# Private Cargo Features

# Work around for sqlx runtime-x feature requirement
# https://github.com/launchbadge/sqlx/issues/1669#issuecomment-1028893261
_sqlx_hack = ["sqlx?/runtime-async-std-rustls"]

[dependencies]
rand = { version = "0.8.5", optional = true, default-features = false}
serde = { version = "1.0.144", optional = true, default-features = false }
sqlx = { version = "0.6.1", optional = true, default-features = false, features = [ "macros" ] }

[dev-dependencies]
criterion = { version = "0.3.6", features = [ "html_reports" ] }
rand = "0.8.5"
serde = { version = "1.0.144", features = [ "derive" ] }
serde_json = "1.0.85"
sqlx = { version = "0.6.2", default-features = false, features = [ "macros", "sqlite", "runtime-async-std-rustls" ] }
async-std = "1.12.0"

[[test]]
name = "rand"
required-features = ["rand"]

[[test]]
name = "serde"
required-features = ["serde"]

[[test]]
name = "sqlx"
required-features = ["sqlx"]

[[bench]]
name = "id64"
harness = false

[[example]]
name = "github_usage_1"
path = "examples/github/usage_1.rs"

[[example]]
name = "github_usage_2"
path = "examples/github/usage_2.rs"

[[example]]
name = "github_usage_rand"
path = "examples/github/usage_rand.rs"
required-features = ["rand"]

[[example]]
name = "github_usage_serde"
path = "examples/github/usage_serde.rs"
required-features = ["serde"]

[[example]]
name = "github_usage_sqlx"
path = "examples/github/usage_sqlx.rs"
required-features = ["sqlx"]
