name: Publish to Crates.io

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    environment:
      name: crates.io
      url: https://crates.io/crates/base64id

    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: cargo publish --verbose