name: Rust Validation

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: cargo fmt
      run: cargo fmt --verbose --check
    
  validate:
    name: Build and Test
    runs-on: ubuntu-latest
    
    needs: format

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --release --workspace --verbose
    - name: Build
      run: cargo build --release --workspace --verbose
    - name: Tests
      run: cargo test --release --workspace --verbose
    - name: Packaging Test
      run: cargo package --workspace --verbose

  validate-all:
    name: Build and Test (All Features)
    runs-on: ubuntu-latest

    needs: format

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --release --workspace --verbose --all-features
    - name: Build
      run: cargo build --release --workspace --verbose --all-features
    - name: Tests
      run: cargo test --release --workspace --verbose --all-features
    - name: Packaging Test
      run: cargo package --workspace --verbose --all-features